services:
  postgres:
    container_name: heroic-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    # Docker sẽ đọc file từ biến ENV_FILE truyền vào từ lệnh run
    env_file:
      - ${ENV_FILE}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - heroic-network

  api:
    container_name: heroic-api
    profiles: ["deploy"] 
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3102:3102"
    volumes:
      - /Users/phanha/Desktop/Project/Heroic/heroic-images:/app/uploads
      - ./logs:/app/logs
    networks:
      - heroic-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  heroic-network:
    driver: bridge