services:
  postgres:
    container_name: heroic-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env.development} # Mặc định là .env.development nếu không truyền
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - heroic-network
    healthcheck:
      # Sử dụng $$ để ép Docker đọc biến môi trường nội bộ của Container
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  api:
    container_name: heroic-api
    profiles: ["deploy"] 
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env.development}
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3103:3103"
    volumes:
      - /Users/phanha/Desktop/Project/Heroic/heroic-images:/app/uploads
      - ./logs:/app/logs
    networks:
      - heroic-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  heroic-network:
    driver: bridge